import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms and Conditions for using PakTechSalary — your guide to our policies and usage terms.",
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-14 sm:py-20">
      <h1 className="text-3xl sm:text-4xl font-bold mb-3">Terms &amp; Conditions</h1>
      <p className="text-sm text-muted mb-10">Last updated: February 13, 2026</p>

      <div className="prose-custom space-y-8">
        <section>
          <h2 className="text-xl font-bold mb-3">1. Acceptance of Terms</h2>
          <p className="text-muted leading-relaxed">
            By accessing and using PakTechSalary (&quot;the Site&quot;), you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, please do not use our website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">2. Description of Services</h2>
          <p className="text-muted leading-relaxed mb-3">
            PakTechSalary provides the following free services to users in Pakistan and beyond:
          </p>
          <ul className="list-disc ml-5 space-y-1.5 text-muted">
            <li><strong>Salary Guides</strong> — estimated salary ranges for technology roles in Pakistan</li>
            <li><strong>Career Tools</strong> — including a salary-after-tax calculator, salary comparison tool, freelance rate calculator, and AI-powered resume strength checker</li>
            <li><strong>Resources</strong> — career guides, tips, and educational articles</li>
            <li><strong>Courses</strong> — curated course recommendations with links to external platforms</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">3. Disclaimer of Accuracy</h2>
          <p className="text-muted leading-relaxed">
            The salary data, tax calculations, and career advice provided on this Site are for <strong>informational purposes only</strong>. While we strive to provide accurate and up-to-date information:
          </p>
          <ul className="list-disc ml-5 space-y-1.5 text-muted mt-3">
            <li>Salary figures are estimates based on market research and may not reflect actual compensation at any specific company</li>
            <li>Tax calculations are based on publicly available FBR tax slabs and may not account for all deductions, allowances, or individual circumstances</li>
            <li>AI-powered resume analysis is generated by Google Gemini and should be used as guidance, not professional career advice</li>
            <li>Course recommendations link to third-party platforms — we do not guarantee the quality, pricing, or availability of those courses</li>
          </ul>
          <p className="text-muted leading-relaxed mt-3">
            <strong>We are not a registered tax consultancy, recruitment agency, or career counseling service.</strong> Always consult qualified professionals for financial, legal, or career decisions.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">4. User Responsibilities</h2>
          <p className="text-muted leading-relaxed mb-3">By using our Site, you agree to:</p>
          <ul className="list-disc ml-5 space-y-1.5 text-muted">
            <li>Use the Site only for lawful purposes</li>
            <li>Not submit false, misleading, or harmful content</li>
            <li>Not attempt to gain unauthorized access to our systems or services</li>
            <li>Not use automated tools (bots, scrapers) to extract data from our Site without permission</li>
            <li>Not upload malicious files to our Resume Checker tool</li>
            <li>Not reproduce, redistribute, or republish our content without prior written consent</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">5. AI Resume Analyzer Terms</h2>
          <p className="text-muted leading-relaxed">
            Our AI Resume Strength Checker uses Google Gemini to analyze resume text you submit. By using this tool:
          </p>
          <ul className="list-disc ml-5 space-y-1.5 text-muted mt-3">
            <li>You consent to your resume text being sent to Google&apos;s AI API for processing</li>
            <li>You acknowledge that AI-generated feedback is not a substitute for professional career counseling</li>
            <li>We do not permanently store your resume text — it is processed in real-time and discarded</li>
            <li>You are responsible for removing any sensitive personal information before submission</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">6. Intellectual Property</h2>
          <p className="text-muted leading-relaxed">
            All content on PakTechSalary — including text, graphics, logos, tool functionality, and page layouts — is the intellectual property of PakTechSalary unless otherwise stated. You may not copy, modify, distribute, or republish any content without our explicit permission.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">7. Third-Party Links</h2>
          <p className="text-muted leading-relaxed">
            Our Site contains links to third-party websites including Coursera, Udemy, and WhatsApp. We are not responsible for the content, privacy practices, or availability of these external sites. Clicking on third-party links is at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">8. Advertising</h2>
          <p className="text-muted leading-relaxed">
            We display advertisements through Google AdSense to support the free services we provide. These ads may use cookies and tracking technologies to serve personalized content. By using our Site, you acknowledge the presence of advertisements and agree to the use of cookies as described in our <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">9. Limitation of Liability</h2>
          <p className="text-muted leading-relaxed">
            PakTechSalary shall not be held liable for any direct, indirect, incidental, or consequential damages arising from your use of the Site, reliance on salary data, tax calculations, AI analysis results, or any actions taken based on information provided on this Site.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">10. Modifications</h2>
          <p className="text-muted leading-relaxed">
            We reserve the right to modify these Terms and Conditions at any time without prior notice. Changes become effective immediately upon posting. Your continued use of the Site constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">11. Governing Law</h2>
          <p className="text-muted leading-relaxed">
            These Terms and Conditions are governed by the laws of Pakistan. Any disputes arising from the use of this Site shall be subject to the jurisdiction of the courts in Pakistan.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3">12. Contact Us</h2>
          <p className="text-muted leading-relaxed">
            If you have questions about these Terms, please contact us at:
          </p>
          <ul className="list-disc ml-5 space-y-1.5 text-muted mt-2">
            <li>Email: <a href="mailto:paktechhjobs@gmail.com" className="text-primary hover:underline">paktechhjobs@gmail.com</a></li>
            <li>Website: <a href="/" className="text-primary hover:underline">paktechsalary.com</a></li>
          </ul>
        </section>
      </div>
    </div>
  );
}
